# Generated by Django 5.2 on 2025-06-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFTReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('wallet_address', models.CharField(max_length=80)),
                ('nft_type', models.CharField(choices=[('blackNFT', 'Black Diamond NFT'), ('greenNFT', 'Green Diamond NFT'), ('blueNFT', 'Blue Diamond NFT'), ('redNFT', 'Red Diamond NFT'), ('flawlessNFT', 'Flawless Diamond NFT')])),
                ('dit_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('reward_collection_date', models.DateTimeField(auto_now_add=True)),
                ('reward_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'nft_reward',
            },
        ),
    ]
