# Generated by Django 5.2 on 2026-01-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('usdt_amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('receiver_address', models.CharField(max_length=40)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('has_dragon', models.BooleanField(default=False)),
                ('dragon_delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
