# Generated by Django 5.2 on 2026-01-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="receiver_address",
            field=models.CharField(max_length=50),
        ),
    ]
