# Generated by Django 5.2 on 2026-02-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_donation_receiver_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='amount',
            new_name='dit_amount',
        ),
    ]
