# Generated by Django 5.2 on 2026-02-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0003_rename_amount_donation_dit_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donation",
            old_name="purchase_date",
            new_name="donated_at",
        ),
    ]
