# Generated by Django 5.2 on 2026-02-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_type', models.CharField(choices=[('RED', 'Red NFT'), ('GREEN', 'Green NFT'), ('BLUE', 'Blue NFT'), ('BLACK', 'Black NFT'), ('DRAGON', 'Dragon NFT'), ('FLAWLESS_DIAMOND', 'Flawless Diamond NFT')], db_index=True, max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=6, help_text='Total DIT amount distributed for this NFT type', max_digits=20)),
                ('per_wallet_amount', models.DecimalField(decimal_places=6, help_text='DIT amount per wallet', max_digits=20)),
                ('wallet_count', models.IntegerField(help_text='Number of wallets that received rewards')),
                ('transaction_hash', models.CharField(db_index=True, help_text='Blockchain transaction hash', max_length=66, unique=True)),
                ('block_number', models.BigIntegerField(db_index=True, help_text='Block number where distribution occurred')),
                ('distributed_at', models.DateTimeField(db_index=True, help_text='Timestamp when rewards were distributed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reward Distribution',
                'verbose_name_plural': 'Reward Distributions',
                'ordering': ['-distributed_at'],
                'indexes': [models.Index(fields=['-distributed_at', 'nft_type'], name='diora_rewar_distrib_cd1e54_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, help_text="User's wallet address", max_length=42)),
                ('amount', models.DecimalField(decimal_places=6, help_text='Amount of DIT claimed', max_digits=20)),
                ('transaction_hash', models.CharField(db_index=True, help_text='Blockchain transaction hash', max_length=66, unique=True)),
                ('block_number', models.BigIntegerField(db_index=True, help_text='Block number where claim occurred')),
                ('claimed_at', models.DateTimeField(db_index=True, help_text='Timestamp when rewards were claimed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Reward Claim',
                'verbose_name_plural': 'User Reward Claims',
                'ordering': ['-claimed_at'],
                'indexes': [models.Index(fields=['wallet_address', '-claimed_at'], name='diora_rewar_wallet__7cfb1b_idx')],
            },
        ),
    ]
