# Generated by Django 5.2 on 2026-02-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diora_reward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarddistribution',
            name='log_index',
            field=models.IntegerField(default=0, help_text='Event log index within the transaction'),
        ),
        migrations.AddField(
            model_name='userrewardclaim',
            name='log_index',
            field=models.IntegerField(default=0, help_text='Event log index within the transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rewarddistribution',
            name='transaction_hash',
            field=models.CharField(db_index=True, help_text='Blockchain transaction hash', max_length=66),
        ),
        migrations.AlterField(
            model_name='userrewardclaim',
            name='transaction_hash',
            field=models.CharField(db_index=True, help_text='Blockchain transaction hash', max_length=66),
        ),
        migrations.AlterUniqueTogether(
            name='rewarddistribution',
            unique_together={('transaction_hash', 'log_index')},
        ),
        migrations.AlterUniqueTogether(
            name='userrewardclaim',
            unique_together={('transaction_hash', 'log_index')},
        ),
    ]
