# Generated by Django 5.2 on 2026-02-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diora_reward', '0002_rewarddistribution_log_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrewardclaim',
            name='log_index',
            field=models.IntegerField(default=0, help_text='Event log index within the transaction'),
        ),
    ]
