# Generated by Django 5.2 on 2026-02-13 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diora_reward", "0003_alter_userrewardclaim_log_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(
                        db_index=True, help_text="User's wallet address", max_length=42
                    ),
                ),
                (
                    "nft_type",
                    models.CharField(
                        choices=[
                            ("RED", "Red NFT"),
                            ("GREEN", "Green NFT"),
                            ("BLUE", "Blue NFT"),
                            ("BLACK", "Black NFT"),
                            ("DRAGON", "Dragon NFT"),
                            ("FLAWLESS_DIAMOND", "Flawless Diamond NFT"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "dit_amount",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Pending DIT amount for this wallet",
                        max_digits=20,
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether reward has been sent to blockchain",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when reward was sent to blockchain",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "distribution",
                    models.ForeignKey(
                        help_text="Related reward distribution batch",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_rewards",
                        to="diora_reward.rewarddistribution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending Reward",
                "verbose_name_plural": "Pending Rewards",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet_address", "is_sent"],
                        name="diora_rewar_wallet__5e028c_idx",
                    ),
                    models.Index(
                        fields=["nft_type", "-created_at"],
                        name="diora_rewar_nft_typ_88f693_idx",
                    ),
                ],
            },
        ),
    ]
