# Generated by Django 5.2 on 2025-10-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('crypto_currency', models.CharField(max_length=50)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('receiver_address', models.CharField(max_length=255)),
                ('membership_added', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'diora_membership',
                'verbose_name_plural': 'diora_memberships',
                'db_table': 'diora_membership',
            },
        ),
    ]
