# Generated by Django 5.2 on 2025-10-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
