# Generated by Django 5.2 on 2025-12-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membership_email_membership_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'DIORA voucher', 'verbose_name_plural': 'DIORA voucher'},
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='membership_added',
            new_name='email_sent',
        ),
        migrations.AddField(
            model_name='membership',
            name='voucher_sent',
            field=models.BooleanField(default=False),
        ),
    ]
