# Generated by Django 5.2 on 2025-04-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dit_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('usdt_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('crypto_currency', models.CharField(max_length=50)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('receiver_address', models.CharField(max_length=255)),
                ('tokens_delivered', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'presale',
            },
        ),
    ]
