# Generated by Django 5.2 on 2025-06-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='presale',
            table='diamond_token_store',
        ),
    ]
