# Generated by Django 5.2 on 2025-10-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0002_alter_presale_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presale',
            options={'verbose_name': 'diamond token store', 'verbose_name_plural': 'diamond token store'},
        ),
    ]
