# Generated by Django 5.2 on 2025-10-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('time', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
